export let constants = {
    RECEIVED_PAGELIST,
    GETTING_PAGELIST,
    RECEIVED_PAGEDETAIL,
    GETTING_PAGEDETAIL,
    CHANGE_TAB,
    TAB_FIELD_CHANGED_VALUE,
    SETTINGS_FIELD_CHANGED_VALUE,
    SAVING_PAGEDETAIL,
    SAVED_PAGEDETAIL
};