export const constants = {
    RECEIVED_PAGELIST: 'RECEIVED_PAGELIST',
    GETTING_PAGELIST: 'GETTING_PAGELIST',
    RECEIVED_PAGEDETAIL: 'RECEIVED_PAGEDETAIL',
    GETTING_PAGEDETAIL: 'GETTING_PAGEDETAIL',
    CHANGE_TAB: 'CHANGE_TAB',
    TAB_FIELD_CHANGED_VALUE: 'TAB_FIELD_CHANGED_VALUE',
    SETTINGS_FIELD_CHANGED_VALUE: 'SETTINGS_FIELD_CHANGED_VALUE',
    SAVING_PAGEDETAIL: 'SAVING_PAGEDETAIL',
    SAVED_PAGEDETAIL: 'SAVED_PAGEDETAIL'
};