export const constants = {
    GET_CONTENT_LIST: 'GET_CONTENT_LIST',
    GET_CONTENT_LIST_PENDING: 'GET_CONTENT_LIST_PENDING',
    GET_CONTENT_LIST_FULFILLED: 'GET_CONTENT_LIST_FULFILLED',
    GET_CONTENT_DETAIL: 'GET_CONTENT_DETAIL',
    GET_CONTENT_DETAIL_PENDING: 'GET_CONTENT_DETAIL_PENDING',
    GET_CONTENT_DETAIL_FULFILLED: 'GET_CONTENT_DETAIL_FULFILLED', 
    GET_CONTENT_DETAIL_UNITTYPE: 'GET_CONTENT_DETAIL_UNITTYPE',
    GET_CONTENT_DETAIL_UNITTYPE_PENDING: 'GET_CONTENT_DETAIL_UNITTYPE_PENDING',
    GET_CONTENT_DETAIL_UNITTYPE_FULFILLED: 'GET_CONTENT_DETAIL_UNITTYPE_FULFILLED', 
    RECEIVED_PAGEDETAIL: 'RECEIVED_PAGEDETAIL',
    GETTING_PAGEDETAIL: 'GETTING_PAGEDETAIL',
    CHANGE_TAB: 'CHANGE_TAB',
    TAB_FIELD_CHANGED_VALUE: 'TAB_FIELD_CHANGED_VALUE',
    SETTINGS_FIELD_CHANGED_VALUE: 'SETTINGS_FIELD_CHANGED_VALUE',
    SAVING_PAGEDETAIL: 'SAVING_PAGEDETAIL',
    SAVED_PAGEDETAIL: 'SAVED_PAGEDETAIL'
};