export const constants = {
    content: {
        GET_CONTENT_LIST: 'GET_CONTENT_LIST',
        GET_CONTENT_LIST_PENDING: 'GET_CONTENT_LIST_PENDING',
        GET_CONTENT_LIST_FULFILLED: 'GET_CONTENT_LIST_FULFILLED',
        GET_CONTENT_UNITS_LIST: 'GET_CONTENT_UNITS_LIST',
        GET_CONTENT_UNITS_LIST_PENDING: 'GET_CONTENT_UNITS_LIST_PENDING',
        GET_CONTENT_UNITS_LIST_FULFILLED: 'GET_CONTENT_UNITS_LIST_FULFILLED',
        GET_CONTENT_DETAIL: 'GET_CONTENT_DETAIL',
        GET_CONTENT_DETAIL_PENDING: 'GET_CONTENT_DETAIL_PENDING',
        GET_CONTENT_DETAIL_FULFILLED: 'GET_CONTENT_DETAIL_FULFILLED', 
        GET_CONTENT_DETAIL_UNITTYPE: 'GET_CONTENT_DETAIL_UNITTYPE',
        GET_CONTENT_DETAIL_UNITTYPE_PENDING: 'GET_CONTENT_DETAIL_UNITTYPE_PENDING',
        GET_CONTENT_DETAIL_UNITTYPE_FULFILLED: 'GET_CONTENT_DETAIL_UNITTYPE_FULFILLED',
        GET_UPDATED_CONTENT_FIELD: 'GET_UPDATED_CONTENT_FIELD',
        POST_CONTENT_DETAIL: 'POST_CONTENT_DETAIL',
        POST_CONTENT_DETAIL_PENDING: 'POST_CONTENT_DETAIL_PENDING',
        POST_CONTENT_DETAIL_FULFILLED: 'POST_CONTENT_DETAIL_FULFILLED',
        EDITIING_CONTENT: 'EDITIING_CONTENT',
        CREATE_UNIT: 'CREATE_UNIT',
        CREATE_CONTENT: 'CREATE_CONTENT',
        CREATE_CONTENT_PENDING: 'CREATE_CONTENT_PENDING',
        CREATE_CONTENT_FULFILLED: 'CREATE_CONTENT_FULFILLED',
        
    },
    units: {
        GET_UNITS_LIST: 'GET_UNITS_LIST',
        GET_UNITS_LIST_PENDING: 'GET_UNITS_LIST_PENDING',
        GET_UNITS_LIST_FULFILLED: 'GET_UNITS_LIST_FULFILLED',
        GET_UNITS_DETAIL: 'GET_UNITS_DETAIL',
        GET_UNITS_DETAIL_PENDING: 'GET_UNITS_DETAIL_PENDING',
        GET_UNITS_DETAIL_FULFILLED: 'GET_UNITS_DETAIL_FULFILLED'
    },
    unitFields: {
        GET_UNITFIELDS_LIST: 'GET_UNITFIELDS_LIST',
        GET_UNITFIELDS_LIST_PENDING: 'GET_UNITFIELDS_LIST_PENDING',
        GET_UNITFIELDS_LIST_FULFILLED: 'GET_UNITFIELDS_LIST_FULFILLED',
        GET_UNITFIELDS_DETAIL: 'GET_UNITFIELDS_DETAIL',
        GET_UNITFIELDS_DETAIL_PENDING: 'GET_UNITFIELDS_DETAIL_PENDING',
        GET_UNITFIELDS_DETAIL_FULFILLED: 'GET_UNITFIELDS_DETAIL_FULFILLED'
    },
    user: {
        SAVING_USER: 'SAVING_USER',
        SAVING_USER_PENDING: 'SAVING_USER_PENDING',
        SAVING_USER_FULFILLED: 'SAVING_USER_FULFILLED'
    }
};